name: Build and Deploy
on: push

jobs:  
  containerization:
    name: Containerizing Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Container Registry
      uses: docker/login-action@v1 
      with:
        username: nologin
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        registry: rg.fr-par.scw.cloud/achampion
    - name: Build Web App
      run: |
        docker build . -t rg.fr-par.scw.cloud/achampion/antoinechampion-com:latest
        docker push rg.fr-par.scw.cloud/achampion/antoinechampion-com:latest

  deployment:
    name: Deploying Kubernetes resources
    needs: [containerization]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - name: Update K8S resources
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: |
          apply -f k8s.yaml          
    - name: Roll out old pods
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: |
          delete pods -l app=antoinechampion-com 
          